---
title: " Descriptive and Correlational Analysis on Survey Questionnaires related to Brexit"
author: "Ansh_Bharadwaj"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
star=read.csv("C:/Users/ansha/OneDrive/Desktop/DSS/DSS/STAR.csv")
```


```{r}
head(star,n=3)
```
```{r}
dim(star)
```
```{r}
mean(star$reading)
```
```{r}
mean(star$graduated)
```
```{r}
star$classtype=="small"
```
```{r}
ifelse(star$classtype=="small",1,0)
```
```{r}
star$small=ifelse(star$classtype=="small",1,0)
```
```{r}
mean(star$reading[star$small==1])
```
```{r}
mean(star$reading[star$small==0])
```
```{r}
mean(star$reading[star$small==1])-mean(star$reading[star$small==0])
```
```{r}
mean(star$math[star$small==1])-mean(star$math[star$small==0])
```
```{r}
mean(star$graduated[star$small==1])
```
```{r}
mean(star$graduated[star$small==0])
```
```{r}
install.packages("remotes")
remotes::install_github("rstudio/learnr")
remotes::install_github("rstudio-education/gradethis")
remotes::install_github("ellaudet/dsslearnr")

```

```{r}
learnr::run_tutorial("01-introduction", package = "dsslearnr")
```
```{r}

```
```{r}
bes=read.csv("C:/Users/ansha/OneDrive/Desktop/DSS/DSS/BES.csv")
```

```{r}
head(bes)
```
```{r}
bes$quit=ifelse(bes$vote=="leave",1,ifelse(bes$vote=="stay",0,NA))
```
```{r}
dim(bes)
```
```{r}
table(bes$vote)
```
```{r}
freq_table<-table(bes$vote)
```

```{r}
prop.table(freq_table)
```
```{r}
age_leave=bes$vote[bes$age>60]
age_leave

```
```{r}
edu_ftable<-table(bes$education,exclude=NULL)
```
```{r}
prop.table(edu_ftable)
```
```{r}
sum(bes$leave,na.rm=TRUE)
```
```{r}
mean(bes$leave,na.rm=TRUE)
```
```{r}
bes1=na.omit(bes)
```
```{r}
dim(bes1)
```
```{r}
head(bes)
```
```{r}
head(bes1)
```
```{r}
leave_ed=table(bes1$leave,bes1$education)
```
```{r}
prop.table(leave_ed)
```
```{r}
prop.table(leave_ed,margin = 1)

```
```{r}
prop.table(leave_ed,margin=2)
```

```{r}
hist(bes1$age)
```
```{r}
hist(bes1$age[bes$leave==1])
hist(bes1$age[bes$leave==0])
```
```{r}
hist(bes1$age[bes1$education==1])
hist(bes1$age[bes1$education==4])
```
```{r}
hist(bes1$age[bes1$education==1],freq=FALSE)
hist(bes1$age[bes1$education==4],freq=FALSE)
```
```{r}
hist(bes1$age[bes1$leave==1],freq=FALSE)
hist(bes1$age[bes1$leave==0],freq=FALSE)
```
```{r}
mean(bes1$age[bes1$leave==1])
mean(bes1$age[bes1$leave==0])

```
```{r}
median(bes1$age[bes1$leave==1])
median(bes1$age[bes1$leave==0])

```
```{r}
sd(bes1$age[bes1$leave==1])
sd(bes1$age[bes1$leave==0])
```
```{r}
bes1$high_ed=ifelse(bes1$education>=3,1,0)
```
```{r}
hist(bes1$age[bes1$high_ed==1],freq=FALSE)
hist(bes1$age[bes1$high_ed==0],freq=FALSE)
```
```{r}
districts=read.csv("C:/Users/ansha/OneDrive/Desktop/DSS/DSS/UK_districts.csv")
```
```{r}
head(districts)

```
```{r}
dim(districts)
```
```{r}
districts1=na.omit(districts)
dim(districts1)
```
```{r}
plot(districts1$high_education,districts1$leave)
abline(v=mean(districts1$high_education),lty="dashed")
abline(h=mean(districts1$leave),lty="dashed")
```
```{r}
cor(districts1$high_education,districts1$leave)
```













